# Generated by Django 4.2.2 on 2023-07-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor')], default='instructor', max_length=150),
        ),
    ]
