version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - ./docker-backend.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
