version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    environment:
      - NEXT_APP_BACKEND_URL=http://localhost:8080
