# Generated by Django 4.2.2 on 2023-07-09 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnquest', '0003_rename_cartcourses_cartcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'course')},
        ),
    ]
