# Generated by Django 4.2.2 on 2023-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnquest', '0005_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(default='Lesson summary - old version'),
            preserve_default=False,
        ),
    ]
